# The path to the local model directory or Hugging Face repo.
model: "mlx-community/gemma-3-1b-it-bf16"
# Whether or not to train (boolean)
train: true

# Directory with {train, valid, test}.jsonl files
data: "data"

fine_tune_type: lora

# The PRNG seed
seed: 0

# Number of layers to fine-tune
num_layers: 16

# Minibatch size.
batch_size: 1

# Iterations to train for.
iters: 40000

# Number of validation batches, -1 uses the entire validation set.
val_batches: 40

# Adam learning rate.
learning_rate: 1e-6

# Number of training steps between loss reporting.
steps_per_report: 10

# Number of training steps between validations.
steps_per_eval: 100

# Load path to resume training with the given adapter weights.
resume_adapter_file:

# Save/load path for the trained adapter weights.
adapter_path: "adapters"

# Save the model every N iterations.
save_every: 2000

# Evaluate on the test set after training
test: false

# Number of test set batches, -1 uses the entire test set.
test_batches: 150

# Maximum sequence length.
max_seq_length: 8192

# Use gradient checkpointing to reduce memory use.
grad_checkpoint: true

# LoRA parameters can only be specified in a config file
lora_parameters:
  # The layer keys to apply LoRA to.
  # These will be applied for the last lora_layers
  keys: ['mlp.gate_proj', 'mlp.down_proj', 'self_attn.q_proj', 'mlp.up_proj', 'self_attn.o_proj','self_attn.v_proj', 'self_attn.k_proj']
#  keys: [ 'self_attn.v_proj', 'self_attn.k_proj' ]
#  keys: ["self_attn.q_proj", "self_attn.v_proj"]
  rank: 64
  alpha: 128
  scale: 10.0
  dropout: 0

# Schedule can only be specified in a config file, uncomment to use.
#lr_schedule:
#  name: cosine_decay
##  warmup: 100 # 0 for no warmup
##  warmup_init: 1e-7 # 0 if not specified
#  arguments: [2e-4, 100, 1e-6] # passed to scheduler